# Specify the version for docker-compose.yml
version: "3"

services:
  purreads_db:
    container_name: purreads_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
      NEW_RELIC_LICENSE: ${NEW_RELIC_LICENSE}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/purreads_data

  api:
    container_name: purreads_api
    build: .
    env_file: .env.docker
    environment:
      DB_HOST: purreads_db
    ports:
      - "8080:8080"
    depends_on:
      - purreads_db
    restart: "on-failure"

volumes:
  data: {}
