// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewBook struct {
	Title  string `json:"title"`
	Author string `json:"author"`
}

type NewCat struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
}
